In [1]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mlxtend in c:\users\rhiu\appdata\roaming\python\python313\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from mlxtend) (1.15.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from mlxtend) (2.2.1)
Requirement already satisfied: pandas>=0.24.2 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from mlxtend) (3.10.3)
Requirement already satisfied: joblib>=0.13.2 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (4.58.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from pandas>=0.24.2->mlxtend) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from pandas>=0.24.2->mlxtend) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\rhiu\appdata\roaming\python\python313\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)

In [2]:
import csv
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori , association_rules

In [3]:
data =[]
with open("Market_Basket_Optimisation.csv") as file:
    reader= csv.reader(file,delimiter=',')
    for row in reader:
        data+=[row]

In [4]:
data[:5]

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea']]

In [5]:
len(data)

7501

In [6]:
te = TransactionEncoder()
X = te.fit_transform(data)

In [7]:
te.columns_

[' asparagus',
 'almonds',
 'antioxydant juice',
 'asparagus',
 'avocado',
 'babies food',
 'bacon',
 'barbecue sauce',
 'black tea',
 'blueberries',
 'body spray',
 'bramble',
 'brownies',
 'bug spray',
 'burger sauce',
 'burgers',
 'butter',
 'cake',
 'candy bars',
 'carrots',
 'cauliflower',
 'cereals',
 'champagne',
 'chicken',
 'chili',
 'chocolate',
 'chocolate bread',
 'chutney',
 'cider',
 'clothes accessories',
 'cookies',
 'cooking oil',
 'corn',
 'cottage cheese',
 'cream',
 'dessert wine',
 'eggplant',
 'eggs',
 'energy bar',
 'energy drink',
 'escalope',
 'extra dark chocolate',
 'flax seed',
 'french fries',
 'french wine',
 'fresh bread',
 'fresh tuna',
 'fromage blanc',
 'frozen smoothie',
 'frozen vegetables',
 'gluten free bar',
 'grated cheese',
 'green beans',
 'green grapes',
 'green tea',
 'ground beef',
 'gums',
 'ham',
 'hand protein bar',
 'herb & pepper',
 'honey',
 'hot dogs',
 'ketchup',
 'light cream',
 'light mayo',
 'low fat yogurt',
 'magazines',
 'mashed potato',
 'mayonnaise',
 'meatballs',
 'melons',
 'milk',
 'mineral water',
 'mint',
 'mint green tea',
 'muffins',
 'mushroom cream sauce',
 'napkins',
 'nonfat milk',
 'oatmeal',
 'oil',
 'olive oil',
 'pancakes',
 'parmesan cheese',
 'pasta',
 'pepper',
 'pet food',
 'pickles',
 'protein bar',
 'red wine',
 'rice',
 'salad',
 'salmon',
 'salt',
 'sandwich',
 'shallot',
 'shampoo',
 'shrimp',
 'soda',
 'soup',
 'spaghetti',
 'sparkling water',
 'spinach',
 'strawberries',
 'strong cheese',
 'tea',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'toothpaste',
 'turkey',
 'vegetables mix',
 'water spray',
 'white wine',
 'whole weat flour',
 'whole wheat pasta',
 'whole wheat rice',
 'yams',
 'yogurt cake',
 'zucchini']

In [8]:
df = pd.DataFrame(X,columns = te.columns_)

In [9]:
df.head()

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [10]:
frequent_items = apriori(df,min_support=0.02,use_colnames=True)

In [11]:
frequent_items

      support                           itemsets
0    0.020397                          (almonds)
1    0.033329                          (avocado)
2    0.033729                         (brownies)
3    0.087188                          (burgers)
4    0.030129                           (butter)
..        ...                                ...
98   0.020131  (whole wheat rice, mineral water)
99   0.022930             (spaghetti, olive oil)
100  0.025197              (pancakes, spaghetti)
101  0.021197                (shrimp, spaghetti)
102  0.020931              (tomatoes, spaghetti)

[103 rows x 2 columns]

In [12]:
rules = association_rules(frequent_items,metric = 'confidence',min_threshold=0.1)

In [13]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,1.0,0.013128,1.224818,0.499424,0.120941,0.183552,0.245256
1,(eggs),(burgers),0.179709,0.087188,0.028796,0.160237,1.837830,1.0,0.013128,1.086988,0.555754,0.120941,0.080026,0.245256
2,(burgers),(french fries),0.087188,0.170911,0.021997,0.252294,1.476173,1.0,0.007096,1.108844,0.353384,0.093168,0.098160,0.190499
3,(french fries),(burgers),0.170911,0.087188,0.021997,0.128705,1.476173,1.0,0.007096,1.047650,0.389069,0.093168,0.045482,0.190499
4,(burgers),(mineral water),0.087188,0.238368,0.024397,0.279817,1.173883,1.0,0.003614,1.057552,0.162275,0.081009,0.054420,0.191083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,(spaghetti),(pancakes),0.174110,0.095054,0.025197,0.144717,1.522468,1.0,0.008647,1.058066,0.415518,0.103279,0.054879,0.204897
90,(shrimp),(spaghetti),0.071457,0.174110,0.021197,0.296642,1.703760,1.0,0.008756,1.174209,0.444850,0.094474,0.148363,0.209194
91,(spaghetti),(shrimp),0.174110,0.071457,0.021197,0.121746,1.703760,1.0,0.008756,1.057260,0.500143,0.094474,0.054159,0.209194
92,(tomatoes),(spaghetti),0.068391,0.174110,0.020931,0.306043,1.757755,1.0,0.009023,1.190117,0.462740,0.094465,0.159746,0.213129
93,(spaghetti),(tomatoes),0.174110,0.068391,0.020931,0.120214,1.757755,1.0,0.009023,1.058905,0.521973,0.094465,0.055628,0.213129

In [14]:
rules = rules[['antecedents','consequents','support','confidence']]

In [15]:
rules.head()

      antecedents      consequents   support  confidence
0       (burgers)           (eggs)  0.028796    0.330275
1          (eggs)        (burgers)  0.028796    0.160237
2       (burgers)   (french fries)  0.021997    0.252294
3  (french fries)        (burgers)  0.021997    0.128705
4       (burgers)  (mineral water)  0.024397    0.279817

In [16]:
rules[rules['antecedents']=={'eggs'}]

   antecedents          consequents   support  confidence
1       (eggs)            (burgers)  0.028796    0.160237
11      (eggs)          (chocolate)  0.033196    0.184718
28      (eggs)       (french fries)  0.036395    0.202522
30      (eggs)  (frozen vegetables)  0.021730    0.120920
32      (eggs)          (green tea)  0.025463    0.141691
35      (eggs)               (milk)  0.030796    0.171365
36      (eggs)      (mineral water)  0.050927    0.283383
39      (eggs)           (pancakes)  0.021730    0.120920
40      (eggs)          (spaghetti)  0.036528    0.203264