In [1]:
import csv
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori , association_rules

In [2]:
X = pd.read_csv('Coursetopics.csv')
print(X)

     Intro  DataMining  Survey  Cat Data  Regression  Forecast  DOE  SW
0        1           1       0         0           0         0    0   0
1        0           0       1         0           0         0    0   0
2        0           1       0         1           1         0    0   1
3        1           0       0         0           0         0    0   0
4        1           1       0         0           0         0    0   0
..     ...         ...     ...       ...         ...       ...  ...  ..
360      0           0       0         1           0         0    0   0
361      0           1       0         1           0         0    0   1
362      0           0       0         0           0         0    0   1
363      0           0       0         1           0         0    0   0
364      0           0       0         0           1         0    0   0

[365 rows x 8 columns]

In [3]:
X_bool = X.astype(bool)
X_bool

     Intro  DataMining  Survey  Cat Data  Regression  Forecast    DOE     SW
0     True        True   False     False       False     False  False  False
1    False       False    True     False       False     False  False  False
2    False        True   False      True        True     False  False   True
3     True       False   False     False       False     False  False  False
4     True        True   False     False       False     False  False  False
..     ...         ...     ...       ...         ...       ...    ...    ...
360  False       False   False      True       False     False  False  False
361  False        True   False      True       False     False  False   True
362  False       False   False     False       False     False  False   True
363  False       False   False      True       False     False  False  False
364  False       False   False     False        True     False  False  False

[365 rows x 8 columns]

In [4]:
frequent_items= apriori(X_bool,min_support=2/365,use_colnames=True)

In [5]:
frequent_items

      support                                  itemsets
0    0.394521                                   (Intro)
1    0.178082                              (DataMining)
2    0.186301                                  (Survey)
3    0.208219                                (Cat Data)
4    0.208219                              (Regression)
..        ...                                       ...
143  0.005479  (Forecast, Survey, DOE, Cat Data, Intro)
144  0.008219   (SW, Forecast, Survey, Cat Data, Intro)
145  0.005479        (SW, Survey, DOE, Cat Data, Intro)
146  0.005479      (SW, Survey, Regression, DOE, Intro)
147  0.005479    (SW, DOE, Regression, Cat Data, Intro)

[148 rows x 2 columns]

In [6]:
rules = association_rules(frequent_items,metric = 'confidence',min_threshold=183/365)

In [7]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,"(DataMining, Regression)",(Intro),0.043836,0.394521,0.027397,0.625000,1.584201,1.0,0.010103,1.614612,0.385673,0.066667,0.380656,0.347222
1,"(Survey, Forecast)",(Intro),0.038356,0.394521,0.021918,0.571429,1.448413,1.0,0.006786,1.412785,0.321937,0.053333,0.292178,0.313492
2,"(Survey, SW)",(Intro),0.049315,0.394521,0.032877,0.666667,1.689815,1.0,0.013421,1.816438,0.429395,0.080000,0.449472,0.375000
3,"(Survey, Intro)",(SW),0.060274,0.221918,0.032877,0.545455,2.457912,1.0,0.019501,1.711781,0.631195,0.131868,0.415813,0.346801
4,"(Regression, Cat Data)",(Intro),0.054795,0.394521,0.032877,0.600000,1.520833,1.0,0.011259,1.513699,0.362319,0.078947,0.339367,0.341667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,"(SW, Survey, Intro, Regression)",(DOE),0.005479,0.172603,0.005479,1.000000,5.793651,1.0,0.004534,inf,0.831956,0.031746,1.000000,0.515873
112,"(SW, Survey, DOE, Intro)",(Regression),0.008219,0.208219,0.005479,0.666667,3.201754,1.0,0.003768,2.375342,0.693370,0.025974,0.579008,0.346491
113,"(Survey, Regression, DOE, Intro)",(SW),0.008219,0.221918,0.005479,0.666667,3.004115,1.0,0.003655,2.334247,0.672652,0.024390,0.571596,0.345679
114,"(SW, Survey, Regression)","(DOE, Intro)",0.005479,0.046575,0.005479,1.000000,21.470588,1.0,0.005224,inf,0.958678,0.117647,1.000000,0.558824
115,"(SW, Cat Data, Regression, DOE)",(Intro),0.005479,0.394521,0.005479,1.000000,2.534722,1.0,0.003318,inf,0.608815,0.013889,1.000000,0.506944

In [8]:
rules=rules[['antecedents','consequents','support','confidence']]

In [9]:
rules

                          antecedents   consequents   support  confidence
0            (DataMining, Regression)       (Intro)  0.027397    0.625000
1                  (Survey, Forecast)       (Intro)  0.021918    0.571429
2                        (Survey, SW)       (Intro)  0.032877    0.666667
3                     (Survey, Intro)          (SW)  0.032877    0.545455
4              (Regression, Cat Data)       (Intro)  0.032877    0.600000
..                                ...           ...       ...         ...
111   (SW, Survey, Intro, Regression)         (DOE)  0.005479    1.000000
112          (SW, Survey, DOE, Intro)  (Regression)  0.005479    0.666667
113  (Survey, Regression, DOE, Intro)          (SW)  0.005479    0.666667
114          (SW, Survey, Regression)  (DOE, Intro)  0.005479    1.000000
115   (SW, Cat Data, Regression, DOE)       (Intro)  0.005479    1.000000

[116 rows x 4 columns]

In [10]:
rules[rules['antecedents']=={'SW', 'DOE'}]

  antecedents consequents   support  confidence
9   (SW, DOE)     (Intro)  0.030137     0.52381